using Xtz.StronglyTyped.SourceGenerator;

namespace Xtz.StronglyTyped.ManyTypes.Types
{
    [StrongType] public partial class Types { }
    [StrongType] public partial class Type2 { }
    [StrongType] public partial class Type3 { }
    [StrongType] public partial class Type4 { }
    [StrongType] public partial class Type5 { }
    [StrongType] public partial class Type6 { }
    [StrongType] public partial class Type7 { }
    [StrongType] public partial class Type8 { }
    [StrongType] public partial class Type9 { }
    [StrongType] public partial class Type10 { }
    [StrongType] public partial class Type11 { }
    [StrongType] public partial class Type12 { }
    [StrongType] public partial class Type13 { }
    [StrongType] public partial class Type14 { }
    [StrongType] public partial class Type15 { }
    [StrongType] public partial class Type16 { }
    [StrongType] public partial class Type17 { }
    [StrongType] public partial class Type18 { }
    [StrongType] public partial class Type19 { }
    [StrongType] public partial class Type20 { }
    [StrongType] public partial class Type21 { }
    [StrongType] public partial class Type22 { }
    [StrongType] public partial class Type23 { }
    [StrongType] public partial class Type24 { }
    [StrongType] public partial class Type25 { }
    [StrongType] public partial class Type26 { }
    [StrongType] public partial class Type27 { }
    [StrongType] public partial class Type28 { }
    [StrongType] public partial class Type29 { }
    [StrongType] public partial class Type30 { }
    [StrongType] public partial class Type31 { }
    [StrongType] public partial class Type32 { }
    [StrongType] public partial class Type33 { }
    [StrongType] public partial class Type34 { }
    [StrongType] public partial class Type35 { }
    [StrongType] public partial class Type36 { }
    [StrongType] public partial class Type37 { }
    [StrongType] public partial class Type38 { }
    [StrongType] public partial class Type39 { }
    [StrongType] public partial class Type40 { }
    [StrongType] public partial class Type41 { }
    [StrongType] public partial class Type42 { }
    [StrongType] public partial class Type43 { }
    [StrongType] public partial class Type44 { }
    [StrongType] public partial class Type45 { }
    [StrongType] public partial class Type46 { }
    [StrongType] public partial class Type47 { }
    [StrongType] public partial class Type48 { }
    [StrongType] public partial class Type49 { }
    [StrongType] public partial class Type50 { }
    [StrongType] public partial class Type51 { }
    [StrongType] public partial class Type52 { }
    [StrongType] public partial class Type53 { }
    [StrongType] public partial class Type54 { }
    [StrongType] public partial class Type55 { }
    [StrongType] public partial class Type56 { }
    [StrongType] public partial class Type57 { }
    [StrongType] public partial class Type58 { }
    [StrongType] public partial class Type59 { }
    [StrongType] public partial class Type60 { }
    [StrongType] public partial class Type61 { }
    [StrongType] public partial class Type62 { }
    [StrongType] public partial class Type63 { }
    [StrongType] public partial class Type64 { }
    [StrongType] public partial class Type65 { }
    [StrongType] public partial class Type66 { }
    [StrongType] public partial class Type67 { }
    [StrongType] public partial class Type68 { }
    [StrongType] public partial class Type69 { }
    [StrongType] public partial class Type70 { }
    [StrongType] public partial class Type71 { }
    [StrongType] public partial class Type72 { }
    [StrongType] public partial class Type73 { }
    [StrongType] public partial class Type74 { }
    [StrongType] public partial class Type75 { }
    [StrongType] public partial class Type76 { }
    [StrongType] public partial class Type77 { }
    [StrongType] public partial class Type78 { }
    [StrongType] public partial class Type79 { }
    [StrongType] public partial class Type80 { }
    [StrongType] public partial class Type81 { }
    [StrongType] public partial class Type82 { }
    [StrongType] public partial class Type83 { }
    [StrongType] public partial class Type84 { }
    [StrongType] public partial class Type85 { }
    [StrongType] public partial class Type86 { }
    [StrongType] public partial class Type87 { }
    [StrongType] public partial class Type88 { }
    [StrongType] public partial class Type89 { }
    [StrongType] public partial class Type90 { }
    [StrongType] public partial class Type91 { }
    [StrongType] public partial class Type92 { }
    [StrongType] public partial class Type93 { }
    [StrongType] public partial class Type94 { }
    [StrongType] public partial class Type95 { }
    [StrongType] public partial class Type96 { }
    [StrongType] public partial class Type97 { }
    [StrongType] public partial class Type98 { }
    [StrongType] public partial class Type99 { }
    [StrongType] public partial class Type100 { }
    [StrongType] public partial class Type101 { }
    [StrongType] public partial class Type102 { }
    [StrongType] public partial class Type103 { }
    [StrongType] public partial class Type104 { }
    [StrongType] public partial class Type105 { }
    [StrongType] public partial class Type106 { }
    [StrongType] public partial class Type107 { }
    [StrongType] public partial class Type108 { }
    [StrongType] public partial class Type109 { }
    [StrongType] public partial class Type110 { }
    [StrongType] public partial class Type111 { }
    [StrongType] public partial class Type112 { }
    [StrongType] public partial class Type113 { }
    [StrongType] public partial class Type114 { }
    [StrongType] public partial class Type115 { }
    [StrongType] public partial class Type116 { }
    [StrongType] public partial class Type117 { }
    [StrongType] public partial class Type118 { }
    [StrongType] public partial class Type119 { }
    [StrongType] public partial class Type120 { }
    [StrongType] public partial class Type121 { }
    [StrongType] public partial class Type122 { }
    [StrongType] public partial class Type123 { }
    [StrongType] public partial class Type124 { }
    [StrongType] public partial class Type125 { }
    [StrongType] public partial class Type126 { }
    [StrongType] public partial class Type127 { }
    [StrongType] public partial class Type128 { }
    [StrongType] public partial class Type129 { }
    [StrongType] public partial class Type130 { }
    [StrongType] public partial class Type131 { }
    [StrongType] public partial class Type132 { }
    [StrongType] public partial class Type133 { }
    [StrongType] public partial class Type134 { }
    [StrongType] public partial class Type135 { }
    [StrongType] public partial class Type136 { }
    [StrongType] public partial class Type137 { }
    [StrongType] public partial class Type138 { }
    [StrongType] public partial class Type139 { }
    [StrongType] public partial class Type140 { }
    [StrongType] public partial class Type141 { }
    [StrongType] public partial class Type142 { }
    [StrongType] public partial class Type143 { }
    [StrongType] public partial class Type144 { }
    [StrongType] public partial class Type145 { }
    [StrongType] public partial class Type146 { }
    [StrongType] public partial class Type147 { }
    [StrongType] public partial class Type148 { }
    [StrongType] public partial class Type149 { }
    [StrongType] public partial class Type150 { }
    [StrongType] public partial class Type151 { }
    [StrongType] public partial class Type152 { }
    [StrongType] public partial class Type153 { }
    [StrongType] public partial class Type154 { }
    [StrongType] public partial class Type155 { }
    [StrongType] public partial class Type156 { }
    [StrongType] public partial class Type157 { }
    [StrongType] public partial class Type158 { }
    [StrongType] public partial class Type159 { }
    [StrongType] public partial class Type160 { }
    [StrongType] public partial class Type161 { }
    [StrongType] public partial class Type162 { }
    [StrongType] public partial class Type163 { }
    [StrongType] public partial class Type164 { }
    [StrongType] public partial class Type165 { }
    [StrongType] public partial class Type166 { }
    [StrongType] public partial class Type167 { }
    [StrongType] public partial class Type168 { }
    [StrongType] public partial class Type169 { }
    [StrongType] public partial class Type170 { }
    [StrongType] public partial class Type171 { }
    [StrongType] public partial class Type172 { }
    [StrongType] public partial class Type173 { }
    [StrongType] public partial class Type174 { }
    [StrongType] public partial class Type175 { }
    [StrongType] public partial class Type176 { }
    [StrongType] public partial class Type177 { }
    [StrongType] public partial class Type178 { }
    [StrongType] public partial class Type179 { }
    [StrongType] public partial class Type180 { }
    [StrongType] public partial class Type181 { }
    [StrongType] public partial class Type182 { }
    [StrongType] public partial class Type183 { }
    [StrongType] public partial class Type184 { }
    [StrongType] public partial class Type185 { }
    [StrongType] public partial class Type186 { }
    [StrongType] public partial class Type187 { }
    [StrongType] public partial class Type188 { }
    [StrongType] public partial class Type189 { }
    [StrongType] public partial class Type190 { }
    [StrongType] public partial class Type191 { }
    [StrongType] public partial class Type192 { }
    [StrongType] public partial class Type193 { }
    [StrongType] public partial class Type194 { }
    [StrongType] public partial class Type195 { }
    [StrongType] public partial class Type196 { }
    [StrongType] public partial class Type197 { }
    [StrongType] public partial class Type198 { }
    [StrongType] public partial class Type199 { }
    [StrongType] public partial class Type200 { }
    [StrongType] public partial class Type201 { }
    [StrongType] public partial class Type202 { }
    [StrongType] public partial class Type203 { }
    [StrongType] public partial class Type204 { }
    [StrongType] public partial class Type205 { }
    [StrongType] public partial class Type206 { }
    [StrongType] public partial class Type207 { }
    [StrongType] public partial class Type208 { }
    [StrongType] public partial class Type209 { }
    [StrongType] public partial class Type210 { }
    [StrongType] public partial class Type211 { }
    [StrongType] public partial class Type212 { }
    [StrongType] public partial class Type213 { }
    [StrongType] public partial class Type214 { }
    [StrongType] public partial class Type215 { }
    [StrongType] public partial class Type216 { }
    [StrongType] public partial class Type217 { }
    [StrongType] public partial class Type218 { }
    [StrongType] public partial class Type219 { }
    [StrongType] public partial class Type220 { }
    [StrongType] public partial class Type221 { }
    [StrongType] public partial class Type222 { }
    [StrongType] public partial class Type223 { }
    [StrongType] public partial class Type224 { }
    [StrongType] public partial class Type225 { }
    [StrongType] public partial class Type226 { }
    [StrongType] public partial class Type227 { }
    [StrongType] public partial class Type228 { }
    [StrongType] public partial class Type229 { }
    [StrongType] public partial class Type230 { }
    [StrongType] public partial class Type231 { }
    [StrongType] public partial class Type232 { }
    [StrongType] public partial class Type233 { }
    [StrongType] public partial class Type234 { }
    [StrongType] public partial class Type235 { }
    [StrongType] public partial class Type236 { }
    [StrongType] public partial class Type237 { }
    [StrongType] public partial class Type238 { }
    [StrongType] public partial class Type239 { }
    [StrongType] public partial class Type240 { }
    [StrongType] public partial class Type241 { }
    [StrongType] public partial class Type242 { }
    [StrongType] public partial class Type243 { }
    [StrongType] public partial class Type244 { }
    [StrongType] public partial class Type245 { }
    [StrongType] public partial class Type246 { }
    [StrongType] public partial class Type247 { }
    [StrongType] public partial class Type248 { }
    [StrongType] public partial class Type249 { }
    [StrongType] public partial class Type250 { }
    [StrongType] public partial class Type251 { }
    [StrongType] public partial class Type252 { }
    [StrongType] public partial class Type253 { }
    [StrongType] public partial class Type254 { }
    [StrongType] public partial class Type255 { }
    [StrongType] public partial class Type256 { }
    [StrongType] public partial class Type257 { }
    [StrongType] public partial class Type258 { }
    [StrongType] public partial class Type259 { }
    [StrongType] public partial class Type260 { }
    [StrongType] public partial class Type261 { }
    [StrongType] public partial class Type262 { }
    [StrongType] public partial class Type263 { }
    [StrongType] public partial class Type264 { }
    [StrongType] public partial class Type265 { }
    [StrongType] public partial class Type266 { }
    [StrongType] public partial class Type267 { }
    [StrongType] public partial class Type268 { }
    [StrongType] public partial class Type269 { }
    [StrongType] public partial class Type270 { }
    [StrongType] public partial class Type271 { }
    [StrongType] public partial class Type272 { }
    [StrongType] public partial class Type273 { }
    [StrongType] public partial class Type274 { }
    [StrongType] public partial class Type275 { }
    [StrongType] public partial class Type276 { }
    [StrongType] public partial class Type277 { }
    [StrongType] public partial class Type278 { }
    [StrongType] public partial class Type279 { }
    [StrongType] public partial class Type280 { }
    [StrongType] public partial class Type281 { }
    [StrongType] public partial class Type282 { }
    [StrongType] public partial class Type283 { }
    [StrongType] public partial class Type284 { }
    [StrongType] public partial class Type285 { }
    [StrongType] public partial class Type286 { }
    [StrongType] public partial class Type287 { }
    [StrongType] public partial class Type288 { }
    [StrongType] public partial class Type289 { }
    [StrongType] public partial class Type290 { }
    [StrongType] public partial class Type291 { }
    [StrongType] public partial class Type292 { }
    [StrongType] public partial class Type293 { }
    [StrongType] public partial class Type294 { }
    [StrongType] public partial class Type295 { }
    [StrongType] public partial class Type296 { }
    [StrongType] public partial class Type297 { }
    [StrongType] public partial class Type298 { }
    [StrongType] public partial class Type299 { }
    [StrongType] public partial class Type300 { }
    [StrongType] public partial class Type301 { }
    [StrongType] public partial class Type302 { }
    [StrongType] public partial class Type303 { }
    [StrongType] public partial class Type304 { }
    [StrongType] public partial class Type305 { }
    [StrongType] public partial class Type306 { }
    [StrongType] public partial class Type307 { }
    [StrongType] public partial class Type308 { }
    [StrongType] public partial class Type309 { }
    [StrongType] public partial class Type310 { }
    [StrongType] public partial class Type311 { }
    [StrongType] public partial class Type312 { }
    [StrongType] public partial class Type313 { }
    [StrongType] public partial class Type314 { }
    [StrongType] public partial class Type315 { }
    [StrongType] public partial class Type316 { }
    [StrongType] public partial class Type317 { }
    [StrongType] public partial class Type318 { }
    [StrongType] public partial class Type319 { }
    [StrongType] public partial class Type320 { }
    [StrongType] public partial class Type321 { }
    [StrongType] public partial class Type322 { }
    [StrongType] public partial class Type323 { }
    [StrongType] public partial class Type324 { }
    [StrongType] public partial class Type325 { }
    [StrongType] public partial class Type326 { }
    [StrongType] public partial class Type327 { }
    [StrongType] public partial class Type328 { }
    [StrongType] public partial class Type329 { }
    [StrongType] public partial class Type330 { }
    [StrongType] public partial class Type331 { }
    [StrongType] public partial class Type332 { }
    [StrongType] public partial class Type333 { }
    [StrongType] public partial class Type334 { }
    [StrongType] public partial class Type335 { }
    [StrongType] public partial class Type336 { }
    [StrongType] public partial class Type337 { }
    [StrongType] public partial class Type338 { }
    [StrongType] public partial class Type339 { }
    [StrongType] public partial class Type340 { }
    [StrongType] public partial class Type341 { }
    [StrongType] public partial class Type342 { }
    [StrongType] public partial class Type343 { }
    [StrongType] public partial class Type344 { }
    [StrongType] public partial class Type345 { }
    [StrongType] public partial class Type346 { }
    [StrongType] public partial class Type347 { }
    [StrongType] public partial class Type348 { }
    [StrongType] public partial class Type349 { }
    [StrongType] public partial class Type350 { }
    [StrongType] public partial class Type351 { }
    [StrongType] public partial class Type352 { }
    [StrongType] public partial class Type353 { }
    [StrongType] public partial class Type354 { }
    [StrongType] public partial class Type355 { }
    [StrongType] public partial class Type356 { }
    [StrongType] public partial class Type357 { }
    [StrongType] public partial class Type358 { }
    [StrongType] public partial class Type359 { }
    [StrongType] public partial class Type360 { }
    [StrongType] public partial class Type361 { }
    [StrongType] public partial class Type362 { }
    [StrongType] public partial class Type363 { }
    [StrongType] public partial class Type364 { }
    [StrongType] public partial class Type365 { }
    [StrongType] public partial class Type366 { }
    [StrongType] public partial class Type367 { }
    [StrongType] public partial class Type368 { }
    [StrongType] public partial class Type369 { }
    [StrongType] public partial class Type370 { }
    [StrongType] public partial class Type371 { }
    [StrongType] public partial class Type372 { }
    [StrongType] public partial class Type373 { }
    [StrongType] public partial class Type374 { }
    [StrongType] public partial class Type375 { }
    [StrongType] public partial class Type376 { }
    [StrongType] public partial class Type377 { }
    [StrongType] public partial class Type378 { }
    [StrongType] public partial class Type379 { }
    [StrongType] public partial class Type380 { }
    [StrongType] public partial class Type381 { }
    [StrongType] public partial class Type382 { }
    [StrongType] public partial class Type383 { }
    [StrongType] public partial class Type384 { }
    [StrongType] public partial class Type385 { }
    [StrongType] public partial class Type386 { }
    [StrongType] public partial class Type387 { }
    [StrongType] public partial class Type388 { }
    [StrongType] public partial class Type389 { }
    [StrongType] public partial class Type390 { }
    [StrongType] public partial class Type391 { }
    [StrongType] public partial class Type392 { }
    [StrongType] public partial class Type393 { }
    [StrongType] public partial class Type394 { }
    [StrongType] public partial class Type395 { }
    [StrongType] public partial class Type396 { }
    [StrongType] public partial class Type397 { }
    [StrongType] public partial class Type398 { }
    [StrongType] public partial class Type399 { }
    [StrongType] public partial class Type400 { }
    [StrongType] public partial class Type401 { }
    [StrongType] public partial class Type402 { }
    [StrongType] public partial class Type403 { }
    [StrongType] public partial class Type404 { }
    [StrongType] public partial class Type405 { }
    [StrongType] public partial class Type406 { }
    [StrongType] public partial class Type407 { }
    [StrongType] public partial class Type408 { }
    [StrongType] public partial class Type409 { }
    [StrongType] public partial class Type410 { }
    [StrongType] public partial class Type411 { }
    [StrongType] public partial class Type412 { }
    [StrongType] public partial class Type413 { }
    [StrongType] public partial class Type414 { }
    [StrongType] public partial class Type415 { }
    [StrongType] public partial class Type416 { }
    [StrongType] public partial class Type417 { }
    [StrongType] public partial class Type418 { }
    [StrongType] public partial class Type419 { }
    [StrongType] public partial class Type420 { }
    [StrongType] public partial class Type421 { }
    [StrongType] public partial class Type422 { }
    [StrongType] public partial class Type423 { }
    [StrongType] public partial class Type424 { }
    [StrongType] public partial class Type425 { }
    [StrongType] public partial class Type426 { }
    [StrongType] public partial class Type427 { }
    [StrongType] public partial class Type428 { }
    [StrongType] public partial class Type429 { }
    [StrongType] public partial class Type430 { }
    [StrongType] public partial class Type431 { }
    [StrongType] public partial class Type432 { }
    [StrongType] public partial class Type433 { }
    [StrongType] public partial class Type434 { }
    [StrongType] public partial class Type435 { }
    [StrongType] public partial class Type436 { }
    [StrongType] public partial class Type437 { }
    [StrongType] public partial class Type438 { }
    [StrongType] public partial class Type439 { }
    [StrongType] public partial class Type440 { }
    [StrongType] public partial class Type441 { }
    [StrongType] public partial class Type442 { }
    [StrongType] public partial class Type443 { }
    [StrongType] public partial class Type444 { }
    [StrongType] public partial class Type445 { }
    [StrongType] public partial class Type446 { }
    [StrongType] public partial class Type447 { }
    [StrongType] public partial class Type448 { }
    [StrongType] public partial class Type449 { }
    [StrongType] public partial class Type450 { }
    [StrongType] public partial class Type451 { }
    [StrongType] public partial class Type452 { }
    [StrongType] public partial class Type453 { }
    [StrongType] public partial class Type454 { }
    [StrongType] public partial class Type455 { }
    [StrongType] public partial class Type456 { }
    [StrongType] public partial class Type457 { }
    [StrongType] public partial class Type458 { }
    [StrongType] public partial class Type459 { }
    [StrongType] public partial class Type460 { }
    [StrongType] public partial class Type461 { }
    [StrongType] public partial class Type462 { }
    [StrongType] public partial class Type463 { }
    [StrongType] public partial class Type464 { }
    [StrongType] public partial class Type465 { }
    [StrongType] public partial class Type466 { }
    [StrongType] public partial class Type467 { }
    [StrongType] public partial class Type468 { }
    [StrongType] public partial class Type469 { }
    [StrongType] public partial class Type470 { }
    [StrongType] public partial class Type471 { }
    [StrongType] public partial class Type472 { }
    [StrongType] public partial class Type473 { }
    [StrongType] public partial class Type474 { }
    [StrongType] public partial class Type475 { }
    [StrongType] public partial class Type476 { }
    [StrongType] public partial class Type477 { }
    [StrongType] public partial class Type478 { }
    [StrongType] public partial class Type479 { }
    [StrongType] public partial class Type480 { }
    [StrongType] public partial class Type481 { }
    [StrongType] public partial class Type482 { }
    [StrongType] public partial class Type483 { }
    [StrongType] public partial class Type484 { }
    [StrongType] public partial class Type485 { }
    [StrongType] public partial class Type486 { }
    [StrongType] public partial class Type487 { }
    [StrongType] public partial class Type488 { }
    [StrongType] public partial class Type489 { }
    [StrongType] public partial class Type490 { }
    [StrongType] public partial class Type491 { }
    [StrongType] public partial class Type492 { }
    [StrongType] public partial class Type493 { }
    [StrongType] public partial class Type494 { }
    [StrongType] public partial class Type495 { }
    [StrongType] public partial class Type496 { }
    [StrongType] public partial class Type497 { }
    [StrongType] public partial class Type498 { }
    [StrongType] public partial class Type499 { }
    [StrongType] public partial class Type500 { }
    [StrongType] public partial class Type501 { }
    [StrongType] public partial class Type502 { }
    [StrongType] public partial class Type503 { }
    [StrongType] public partial class Type504 { }
    [StrongType] public partial class Type505 { }
    [StrongType] public partial class Type506 { }
    [StrongType] public partial class Type507 { }
    [StrongType] public partial class Type508 { }
    [StrongType] public partial class Type509 { }
    [StrongType] public partial class Type510 { }
    [StrongType] public partial class Type511 { }
    [StrongType] public partial class Type512 { }
    [StrongType] public partial class Type513 { }
    [StrongType] public partial class Type514 { }
    [StrongType] public partial class Type515 { }
    [StrongType] public partial class Type516 { }
    [StrongType] public partial class Type517 { }
    [StrongType] public partial class Type518 { }
    [StrongType] public partial class Type519 { }
    [StrongType] public partial class Type520 { }
    [StrongType] public partial class Type521 { }
    [StrongType] public partial class Type522 { }
    [StrongType] public partial class Type523 { }
    [StrongType] public partial class Type524 { }
    [StrongType] public partial class Type525 { }
    [StrongType] public partial class Type526 { }
    [StrongType] public partial class Type527 { }
    [StrongType] public partial class Type528 { }
    [StrongType] public partial class Type529 { }
    [StrongType] public partial class Type530 { }
    [StrongType] public partial class Type531 { }
    [StrongType] public partial class Type532 { }
    [StrongType] public partial class Type533 { }
    [StrongType] public partial class Type534 { }
    [StrongType] public partial class Type535 { }
    [StrongType] public partial class Type536 { }
    [StrongType] public partial class Type537 { }
    [StrongType] public partial class Type538 { }
    [StrongType] public partial class Type539 { }
    [StrongType] public partial class Type540 { }
    [StrongType] public partial class Type541 { }
    [StrongType] public partial class Type542 { }
    [StrongType] public partial class Type543 { }
    [StrongType] public partial class Type544 { }
    [StrongType] public partial class Type545 { }
    [StrongType] public partial class Type546 { }
    [StrongType] public partial class Type547 { }
    [StrongType] public partial class Type548 { }
    [StrongType] public partial class Type549 { }
    [StrongType] public partial class Type550 { }
    [StrongType] public partial class Type551 { }
    [StrongType] public partial class Type552 { }
    [StrongType] public partial class Type553 { }
    [StrongType] public partial class Type554 { }
    [StrongType] public partial class Type555 { }
    [StrongType] public partial class Type556 { }
    [StrongType] public partial class Type557 { }
    [StrongType] public partial class Type558 { }
    [StrongType] public partial class Type559 { }
    [StrongType] public partial class Type560 { }
    [StrongType] public partial class Type561 { }
    [StrongType] public partial class Type562 { }
    [StrongType] public partial class Type563 { }
    [StrongType] public partial class Type564 { }
    [StrongType] public partial class Type565 { }
    [StrongType] public partial class Type566 { }
    [StrongType] public partial class Type567 { }
    [StrongType] public partial class Type568 { }
    [StrongType] public partial class Type569 { }
    [StrongType] public partial class Type570 { }
    [StrongType] public partial class Type571 { }
    [StrongType] public partial class Type572 { }
    [StrongType] public partial class Type573 { }
    [StrongType] public partial class Type574 { }
    [StrongType] public partial class Type575 { }
    [StrongType] public partial class Type576 { }
    [StrongType] public partial class Type577 { }
    [StrongType] public partial class Type578 { }
    [StrongType] public partial class Type579 { }
    [StrongType] public partial class Type580 { }
    [StrongType] public partial class Type581 { }
    [StrongType] public partial class Type582 { }
    [StrongType] public partial class Type583 { }
    [StrongType] public partial class Type584 { }
    [StrongType] public partial class Type585 { }
    [StrongType] public partial class Type586 { }
    [StrongType] public partial class Type587 { }
    [StrongType] public partial class Type588 { }
    [StrongType] public partial class Type589 { }
    [StrongType] public partial class Type590 { }
    [StrongType] public partial class Type591 { }
    [StrongType] public partial class Type592 { }
    [StrongType] public partial class Type593 { }
    [StrongType] public partial class Type594 { }
    [StrongType] public partial class Type595 { }
    [StrongType] public partial class Type596 { }
    [StrongType] public partial class Type597 { }
    [StrongType] public partial class Type598 { }
    [StrongType] public partial class Type599 { }
    [StrongType] public partial class Type600 { }
    [StrongType] public partial class Type601 { }
    [StrongType] public partial class Type602 { }
    [StrongType] public partial class Type603 { }
    [StrongType] public partial class Type604 { }
    [StrongType] public partial class Type605 { }
    [StrongType] public partial class Type606 { }
    [StrongType] public partial class Type607 { }
    [StrongType] public partial class Type608 { }
    [StrongType] public partial class Type609 { }
    [StrongType] public partial class Type610 { }
    [StrongType] public partial class Type611 { }
    [StrongType] public partial class Type612 { }
    [StrongType] public partial class Type613 { }
    [StrongType] public partial class Type614 { }
    [StrongType] public partial class Type615 { }
    [StrongType] public partial class Type616 { }
    [StrongType] public partial class Type617 { }
    [StrongType] public partial class Type618 { }
    [StrongType] public partial class Type619 { }
    [StrongType] public partial class Type620 { }
    [StrongType] public partial class Type621 { }
    [StrongType] public partial class Type622 { }
    [StrongType] public partial class Type623 { }
    [StrongType] public partial class Type624 { }
    [StrongType] public partial class Type625 { }
    [StrongType] public partial class Type626 { }
    [StrongType] public partial class Type627 { }
    [StrongType] public partial class Type628 { }
    [StrongType] public partial class Type629 { }
    [StrongType] public partial class Type630 { }
    [StrongType] public partial class Type631 { }
    [StrongType] public partial class Type632 { }
    [StrongType] public partial class Type633 { }
    [StrongType] public partial class Type634 { }
    [StrongType] public partial class Type635 { }
    [StrongType] public partial class Type636 { }
    [StrongType] public partial class Type637 { }
    [StrongType] public partial class Type638 { }
    [StrongType] public partial class Type639 { }
    [StrongType] public partial class Type640 { }
    [StrongType] public partial class Type641 { }
    [StrongType] public partial class Type642 { }
    [StrongType] public partial class Type643 { }
    [StrongType] public partial class Type644 { }
    [StrongType] public partial class Type645 { }
    [StrongType] public partial class Type646 { }
    [StrongType] public partial class Type647 { }
    [StrongType] public partial class Type648 { }
    [StrongType] public partial class Type649 { }
    [StrongType] public partial class Type650 { }
    [StrongType] public partial class Type651 { }
    [StrongType] public partial class Type652 { }
    [StrongType] public partial class Type653 { }
    [StrongType] public partial class Type654 { }
    [StrongType] public partial class Type655 { }
    [StrongType] public partial class Type656 { }
    [StrongType] public partial class Type657 { }
    [StrongType] public partial class Type658 { }
    [StrongType] public partial class Type659 { }
    [StrongType] public partial class Type660 { }
    [StrongType] public partial class Type661 { }
    [StrongType] public partial class Type662 { }
    [StrongType] public partial class Type663 { }
    [StrongType] public partial class Type664 { }
    [StrongType] public partial class Type665 { }
    [StrongType] public partial class Type666 { }
    [StrongType] public partial class Type667 { }
    [StrongType] public partial class Type668 { }
    [StrongType] public partial class Type669 { }
    [StrongType] public partial class Type670 { }
    [StrongType] public partial class Type671 { }
    [StrongType] public partial class Type672 { }
    [StrongType] public partial class Type673 { }
    [StrongType] public partial class Type674 { }
    [StrongType] public partial class Type675 { }
    [StrongType] public partial class Type676 { }
    [StrongType] public partial class Type677 { }
    [StrongType] public partial class Type678 { }
    [StrongType] public partial class Type679 { }
    [StrongType] public partial class Type680 { }
    [StrongType] public partial class Type681 { }
    [StrongType] public partial class Type682 { }
    [StrongType] public partial class Type683 { }
    [StrongType] public partial class Type684 { }
    [StrongType] public partial class Type685 { }
    [StrongType] public partial class Type686 { }
    [StrongType] public partial class Type687 { }
    [StrongType] public partial class Type688 { }
    [StrongType] public partial class Type689 { }
    [StrongType] public partial class Type690 { }
    [StrongType] public partial class Type691 { }
    [StrongType] public partial class Type692 { }
    [StrongType] public partial class Type693 { }
    [StrongType] public partial class Type694 { }
    [StrongType] public partial class Type695 { }
    [StrongType] public partial class Type696 { }
    [StrongType] public partial class Type697 { }
    [StrongType] public partial class Type698 { }
    [StrongType] public partial class Type699 { }
    [StrongType] public partial class Type700 { }
    [StrongType] public partial class Type701 { }
    [StrongType] public partial class Type702 { }
    [StrongType] public partial class Type703 { }
    [StrongType] public partial class Type704 { }
    [StrongType] public partial class Type705 { }
    [StrongType] public partial class Type706 { }
    [StrongType] public partial class Type707 { }
    [StrongType] public partial class Type708 { }
    [StrongType] public partial class Type709 { }
    [StrongType] public partial class Type710 { }
    [StrongType] public partial class Type711 { }
    [StrongType] public partial class Type712 { }
    [StrongType] public partial class Type713 { }
    [StrongType] public partial class Type714 { }
    [StrongType] public partial class Type715 { }
    [StrongType] public partial class Type716 { }
    [StrongType] public partial class Type717 { }
    [StrongType] public partial class Type718 { }
    [StrongType] public partial class Type719 { }
    [StrongType] public partial class Type720 { }
    [StrongType] public partial class Type721 { }
    [StrongType] public partial class Type722 { }
    [StrongType] public partial class Type723 { }
    [StrongType] public partial class Type724 { }
    [StrongType] public partial class Type725 { }
    [StrongType] public partial class Type726 { }
    [StrongType] public partial class Type727 { }
    [StrongType] public partial class Type728 { }
    [StrongType] public partial class Type729 { }
    [StrongType] public partial class Type730 { }
    [StrongType] public partial class Type731 { }
    [StrongType] public partial class Type732 { }
    [StrongType] public partial class Type733 { }
    [StrongType] public partial class Type734 { }
    [StrongType] public partial class Type735 { }
    [StrongType] public partial class Type736 { }
    [StrongType] public partial class Type737 { }
    [StrongType] public partial class Type738 { }
    [StrongType] public partial class Type739 { }
    [StrongType] public partial class Type740 { }
    [StrongType] public partial class Type741 { }
    [StrongType] public partial class Type742 { }
    [StrongType] public partial class Type743 { }
    [StrongType] public partial class Type744 { }
    [StrongType] public partial class Type745 { }
    [StrongType] public partial class Type746 { }
    [StrongType] public partial class Type747 { }
    [StrongType] public partial class Type748 { }
    [StrongType] public partial class Type749 { }
    [StrongType] public partial class Type750 { }
    [StrongType] public partial class Type751 { }
    [StrongType] public partial class Type752 { }
    [StrongType] public partial class Type753 { }
    [StrongType] public partial class Type754 { }
    [StrongType] public partial class Type755 { }
    [StrongType] public partial class Type756 { }
    [StrongType] public partial class Type757 { }
    [StrongType] public partial class Type758 { }
    [StrongType] public partial class Type759 { }
    [StrongType] public partial class Type760 { }
    [StrongType] public partial class Type761 { }
    [StrongType] public partial class Type762 { }
    [StrongType] public partial class Type763 { }
    [StrongType] public partial class Type764 { }
    [StrongType] public partial class Type765 { }
    [StrongType] public partial class Type766 { }
    [StrongType] public partial class Type767 { }
    [StrongType] public partial class Type768 { }
    [StrongType] public partial class Type769 { }
    [StrongType] public partial class Type770 { }
    [StrongType] public partial class Type771 { }
    [StrongType] public partial class Type772 { }
    [StrongType] public partial class Type773 { }
    [StrongType] public partial class Type774 { }
    [StrongType] public partial class Type775 { }
    [StrongType] public partial class Type776 { }
    [StrongType] public partial class Type777 { }
    [StrongType] public partial class Type778 { }
    [StrongType] public partial class Type779 { }
    [StrongType] public partial class Type780 { }
    [StrongType] public partial class Type781 { }
    [StrongType] public partial class Type782 { }
    [StrongType] public partial class Type783 { }
    [StrongType] public partial class Type784 { }
    [StrongType] public partial class Type785 { }
    [StrongType] public partial class Type786 { }
    [StrongType] public partial class Type787 { }
    [StrongType] public partial class Type788 { }
    [StrongType] public partial class Type789 { }
    [StrongType] public partial class Type790 { }
    [StrongType] public partial class Type791 { }
    [StrongType] public partial class Type792 { }
    [StrongType] public partial class Type793 { }
    [StrongType] public partial class Type794 { }
    [StrongType] public partial class Type795 { }
    [StrongType] public partial class Type796 { }
    [StrongType] public partial class Type797 { }
    [StrongType] public partial class Type798 { }
    [StrongType] public partial class Type799 { }
    [StrongType] public partial class Type800 { }
    [StrongType] public partial class Type801 { }
    [StrongType] public partial class Type802 { }
    [StrongType] public partial class Type803 { }
    [StrongType] public partial class Type804 { }
    [StrongType] public partial class Type805 { }
    [StrongType] public partial class Type806 { }
    [StrongType] public partial class Type807 { }
    [StrongType] public partial class Type808 { }
    [StrongType] public partial class Type809 { }
    [StrongType] public partial class Type810 { }
    [StrongType] public partial class Type811 { }
    [StrongType] public partial class Type812 { }
    [StrongType] public partial class Type813 { }
    [StrongType] public partial class Type814 { }
    [StrongType] public partial class Type815 { }
    [StrongType] public partial class Type816 { }
    [StrongType] public partial class Type817 { }
    [StrongType] public partial class Type818 { }
    [StrongType] public partial class Type819 { }
    [StrongType] public partial class Type820 { }
    [StrongType] public partial class Type821 { }
    [StrongType] public partial class Type822 { }
    [StrongType] public partial class Type823 { }
    [StrongType] public partial class Type824 { }
    [StrongType] public partial class Type825 { }
    [StrongType] public partial class Type826 { }
    [StrongType] public partial class Type827 { }
    [StrongType] public partial class Type828 { }
    [StrongType] public partial class Type829 { }
    [StrongType] public partial class Type830 { }
    [StrongType] public partial class Type831 { }
    [StrongType] public partial class Type832 { }
    [StrongType] public partial class Type833 { }
    [StrongType] public partial class Type834 { }
    [StrongType] public partial class Type835 { }
    [StrongType] public partial class Type836 { }
    [StrongType] public partial class Type837 { }
    [StrongType] public partial class Type838 { }
    [StrongType] public partial class Type839 { }
    [StrongType] public partial class Type840 { }
    [StrongType] public partial class Type841 { }
    [StrongType] public partial class Type842 { }
    [StrongType] public partial class Type843 { }
    [StrongType] public partial class Type844 { }
    [StrongType] public partial class Type845 { }
    [StrongType] public partial class Type846 { }
    [StrongType] public partial class Type847 { }
    [StrongType] public partial class Type848 { }
    [StrongType] public partial class Type849 { }
    [StrongType] public partial class Type850 { }
    [StrongType] public partial class Type851 { }
    [StrongType] public partial class Type852 { }
    [StrongType] public partial class Type853 { }
    [StrongType] public partial class Type854 { }
    [StrongType] public partial class Type855 { }
    [StrongType] public partial class Type856 { }
    [StrongType] public partial class Type857 { }
    [StrongType] public partial class Type858 { }
    [StrongType] public partial class Type859 { }
    [StrongType] public partial class Type860 { }
    [StrongType] public partial class Type861 { }
    [StrongType] public partial class Type862 { }
    [StrongType] public partial class Type863 { }
    [StrongType] public partial class Type864 { }
    [StrongType] public partial class Type865 { }
    [StrongType] public partial class Type866 { }
    [StrongType] public partial class Type867 { }
    [StrongType] public partial class Type868 { }
    [StrongType] public partial class Type869 { }
    [StrongType] public partial class Type870 { }
    [StrongType] public partial class Type871 { }
    [StrongType] public partial class Type872 { }
    [StrongType] public partial class Type873 { }
    [StrongType] public partial class Type874 { }
    [StrongType] public partial class Type875 { }
    [StrongType] public partial class Type876 { }
    [StrongType] public partial class Type877 { }
    [StrongType] public partial class Type878 { }
    [StrongType] public partial class Type879 { }
    [StrongType] public partial class Type880 { }
    [StrongType] public partial class Type881 { }
    [StrongType] public partial class Type882 { }
    [StrongType] public partial class Type883 { }
    [StrongType] public partial class Type884 { }
    [StrongType] public partial class Type885 { }
    [StrongType] public partial class Type886 { }
    [StrongType] public partial class Type887 { }
    [StrongType] public partial class Type888 { }
    [StrongType] public partial class Type889 { }
    [StrongType] public partial class Type890 { }
    [StrongType] public partial class Type891 { }
    [StrongType] public partial class Type892 { }
    [StrongType] public partial class Type893 { }
    [StrongType] public partial class Type894 { }
    [StrongType] public partial class Type895 { }
    [StrongType] public partial class Type896 { }
    [StrongType] public partial class Type897 { }
    [StrongType] public partial class Type898 { }
    [StrongType] public partial class Type899 { }
    [StrongType] public partial class Type900 { }
    [StrongType] public partial class Type901 { }
    [StrongType] public partial class Type902 { }
    [StrongType] public partial class Type903 { }
    [StrongType] public partial class Type904 { }
    [StrongType] public partial class Type905 { }
    [StrongType] public partial class Type906 { }
    [StrongType] public partial class Type907 { }
    [StrongType] public partial class Type908 { }
    [StrongType] public partial class Type909 { }
    [StrongType] public partial class Type910 { }
    [StrongType] public partial class Type911 { }
    [StrongType] public partial class Type912 { }
    [StrongType] public partial class Type913 { }
    [StrongType] public partial class Type914 { }
    [StrongType] public partial class Type915 { }
    [StrongType] public partial class Type916 { }
    [StrongType] public partial class Type917 { }
    [StrongType] public partial class Type918 { }
    [StrongType] public partial class Type919 { }
    [StrongType] public partial class Type920 { }
    [StrongType] public partial class Type921 { }
    [StrongType] public partial class Type922 { }
    [StrongType] public partial class Type923 { }
    [StrongType] public partial class Type924 { }
    [StrongType] public partial class Type925 { }
    [StrongType] public partial class Type926 { }
    [StrongType] public partial class Type927 { }
    [StrongType] public partial class Type928 { }
    [StrongType] public partial class Type929 { }
    [StrongType] public partial class Type930 { }
    [StrongType] public partial class Type931 { }
    [StrongType] public partial class Type932 { }
    [StrongType] public partial class Type933 { }
    [StrongType] public partial class Type934 { }
    [StrongType] public partial class Type935 { }
    [StrongType] public partial class Type936 { }
    [StrongType] public partial class Type937 { }
    [StrongType] public partial class Type938 { }
    [StrongType] public partial class Type939 { }
    [StrongType] public partial class Type940 { }
    [StrongType] public partial class Type941 { }
    [StrongType] public partial class Type942 { }
    [StrongType] public partial class Type943 { }
    [StrongType] public partial class Type944 { }
    [StrongType] public partial class Type945 { }
    [StrongType] public partial class Type946 { }
    [StrongType] public partial class Type947 { }
    [StrongType] public partial class Type948 { }
    [StrongType] public partial class Type949 { }
    [StrongType] public partial class Type950 { }
    [StrongType] public partial class Type951 { }
    [StrongType] public partial class Type952 { }
    [StrongType] public partial class Type953 { }
    [StrongType] public partial class Type954 { }
    [StrongType] public partial class Type955 { }
    [StrongType] public partial class Type956 { }
    [StrongType] public partial class Type957 { }
    [StrongType] public partial class Type958 { }
    [StrongType] public partial class Type959 { }
    [StrongType] public partial class Type960 { }
    [StrongType] public partial class Type961 { }
    [StrongType] public partial class Type962 { }
    [StrongType] public partial class Type963 { }
    [StrongType] public partial class Type964 { }
    [StrongType] public partial class Type965 { }
    [StrongType] public partial class Type966 { }
    [StrongType] public partial class Type967 { }
    [StrongType] public partial class Type968 { }
    [StrongType] public partial class Type969 { }
    [StrongType] public partial class Type970 { }
    [StrongType] public partial class Type971 { }
    [StrongType] public partial class Type972 { }
    [StrongType] public partial class Type973 { }
    [StrongType] public partial class Type974 { }
    [StrongType] public partial class Type975 { }
    [StrongType] public partial class Type976 { }
    [StrongType] public partial class Type977 { }
    [StrongType] public partial class Type978 { }
    [StrongType] public partial class Type979 { }
    [StrongType] public partial class Type980 { }
    [StrongType] public partial class Type981 { }
    [StrongType] public partial class Type982 { }
    [StrongType] public partial class Type983 { }
    [StrongType] public partial class Type984 { }
    [StrongType] public partial class Type985 { }
    [StrongType] public partial class Type986 { }
    [StrongType] public partial class Type987 { }
    [StrongType] public partial class Type988 { }
    [StrongType] public partial class Type989 { }
    [StrongType] public partial class Type990 { }
    [StrongType] public partial class Type991 { }
    [StrongType] public partial class Type992 { }
    [StrongType] public partial class Type993 { }
    [StrongType] public partial class Type994 { }
    [StrongType] public partial class Type995 { }
    [StrongType] public partial class Type996 { }
    [StrongType] public partial class Type997 { }
    [StrongType] public partial class Type998 { }
    [StrongType] public partial class Type999 { }
    [StrongType] public partial class Type1000 { }
}
